### ISSUE TITLE
Clicking on open/close parenthesis selects sexp

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#111]
Maria seems to use a type of paredit, but I couldn't figure out how to slurp/barf, making certain edits quite painful. When you select some text it changes the hover cursor to a hand, encouraging users to select some code and drag it around. This works pretty well, but it's easy to select an unbalanced expression and mess things up.

If clicking on a parenthesis would make the whole balanced expression selected so you can drag it around I think that could be a somewhat intuitive way of restructuring code. It would also encourage people to think in "blocks".

**Comment by mhuebert** [comment]
Thanks for this feedback!

**structural editing**

So, we do have `slurp`, bound to `M1-Shift-K` (where `M1` is ctrl/command depending on platform). But it is understandable that you didn't find it. 

The recommended way to find commands is command-search (`M1-P`, or click `Commands...` in the top bar), but it is currently set to only show commands that are relevant given the current context, which means you would only see `slurp` if you were in a code block with the cursor in a location where `slurp` is possible. This makes it too hard to find commands and should be changed:

- [ ] show non-contextually-relevant commands in command search (#112)

I would also like to add a command _browsing_ interface, where you can traverse commands by category/namespace.

- [ ] command browser (#115)

Barf is not yet implemented.

- [ ] implement barf (#114)

We do need better explanation of the editing commands/etc in Maria. I think this will go in the [editor quickstart](https://dev.maria.cloud/quickstart).

### Selections

When selections are made by the mouse, no attempt is made to 'normalize' the selection to valid (balanced) forms. This is something I'd like to try playing with at some point, but it isn't straightforward, as there are many weird selections you might want to make for valid editing purposes. eg/ in `(1 2)(3 4)`, you might want to select & delete the parens between the 2 and 3. 

I've implemented the 'click on parentheses to select form' a couple of times, and my first attempts didn't feel quite right. A straight override of `click` interrupted the default behaviour of placing a cursor, so it became difficult to put the cursor near parens. I then added a modifier, so `command-click`. I think I got rid of it because it interfered with CodeMirror's multiple cursors behaviour, which there is no way to disable, nor modify the bindings for, and there may have been other issues with attempts to use `alt/option`, I can't remember. In any case I think it is worth revisiting:

- [ ] implement <some-modifier>-Click for selecting a form (#113)

I totally agree with the 'thinking in blocks' idea. I have code lying around somewhere for allowing slurp/barf by using the mouse to drag parens around, which I might be able to re-use here. (search for the word 'physical' at http://px16.matt.is/ for a demo of that)

**Comment by mhuebert** [comment]
I've added `barf`, bound to `M3-Left` (where `M3` is Ctrl on a mac, windows/meta on a PC).

I also added the binding `M3-Right` for slurp.

(Bindings are a huge source of cross-platform pain, so please let me know if these don't work on your system :-).)

**Comment by pedrorgirardi** [comment]
I think **Maria** has the easiest `slurp/barf` keybindings that I've used. It's great for people like me, that is not very good with keybindings. 😅

 Thanks @mhuebert!

**Comment by mhuebert** [comment]
Turned out, the most reliable _and_ simple way to implement this was to augment existing `M1` behaviour. To recap, and explain how mouse selections work:

- `M1` selects form at cursor
- `M1-Shift` expands selection to top-level form
- while holding `M1`, you can move the cursor across the editor, and forms under the cursor will be temporarily selected. You can then *click* to set the selection under the cursor, or *click and drag* to move the form under the cursor. Releasing `M1` without clicking will return the selection/cursor to its pre-`M1` state.

**Comment by plexus** [comment]
> while holding M1, you can move the cursor across the editor, and forms under the cursor will be temporarily selected. You can then click to set the selection under the cursor, or click and drag to move the form under the cursor. Releasing M1 without clicking will return the selection/cursor to its pre-M1 state.

Tried this on dev.maria.cloud, it's a pretty good interaction. After a bit of hovering/clicking around it did get in a bad state, it seems the `M1` got "stuck", so even after releasing it it would still select different forms when moving around.

> I also added the binding M3-Right for slurp.

So this should be Meta=Windows key on Linux? Doesn't seem to work... The paredit way would be C-left/C-right, but I notice those are bound to growing the selection (side note, they both grow the selection, maybe one of them should shrink the selection?). Would it be an option to use the paredit bindings (`C-left/C-right`) for slurp/barf, and `C-Shift-Left/Right` for growing/shrinking selection. given that `Shift` is associated with selecting things?

Loving the overlay that pops up when you hold a modifier. I only just discovered that. I perhaps feel it could pop up a little faster.

**Comment by mhuebert** [comment]
> it seems the M1 got "stuck"

ah, thanks for the feedback. I've just pushed a change that should prevent
more of these cases.

> So this should be Meta=Windows key on Linux? Doesn't seem to work

I continually underestimate how 'captured' the meta key on non-mac systems
is. It seems basically unusable for our purposes.

I've just added `M1-Shift-Right/Left` for slurp/barf, hopefully that will
works. It does on the Windows 10 image I am testing with.

> side note, they both grow the selection, maybe one of them should shrink
the selection?

I think the `down` arrow does what you're looking for. Selections can be
modified with M1-[all arrow keys], where `left/up/right` grow the
selection, and `down` returns the selection (step by step) to the start
position. (`M1-down` could yet be improved to shrink the selection if no
selection stack is present.)

> Would it be an option to use the paredit bindings (C-left/C-right) for
slurp/barf, and C-Shift-Left/Right for growing/shrinking selection. given
that Shift is associated with selecting things?

The commands described above are designed to make selections a faster/more
automatic part of the editing experience, all starting with `M1` so that
simply adding `c/x/v` invokes copy/cut/paste. The idea is that this can
enable various kinds of structural edits with _very_ few key commands or
special names to learn - just Command/Control + arrow keys + cut/copy/paste.

But I like the idea of building on the association `Shift` has with
selecting things, and I've tried something along these lines locally. So
far the friction of an extra modifier seemed too much. I'm not opposed to
it in principle, there are tradeoffs either way, and many limitations
imposed by the various platform keybinding situations.

**Comment by mhuebert** [comment]
(reposting with markdown enabled)

> it seems the M1 got "stuck"

ah, thanks for the feedback. I've just pushed a change that should prevent
more of these cases.

> So this should be Meta=Windows key on Linux? Doesn't seem to work

I continually underestimate how 'captured' the meta key on non-mac systems
is. It seems basically unusable for our purposes.

I've just added `M1-Shift-Right/Left` for slurp/barf, hopefully that will
works. It does on the Windows 10 image I am testing with.

> side note, they both grow the selection, maybe one of them should shrink
the selection?

I think the `down` arrow does what you're looking for. Selections can be
modified with M1-[all arrow keys], where `left/up/right` grow the
selection, and `down` returns the selection (step by step) to the start
position. (`M1-down` could yet be improved to shrink the selection if no
selection stack is present.)

> Would it be an option to use the paredit bindings (C-left/C-right) for
slurp/barf, and C-Shift-Left/Right for growing/shrinking selection. given
that Shift is associated with selecting things?

The commands described above are designed to make selections a faster/more
automatic part of the editing experience, all starting with `M1` so that
simply adding `c/x/v` invokes copy/cut/paste. The idea is that this can
enable various kinds of structural edits with _very_ few key commands or
special names to learn - just Command/Control + arrow keys + cut/copy/paste.

But I like the idea of building on the association `Shift` has with
selecting things, and I've tried something along these lines locally. So
far the friction of an extra modifier seemed too much. I'm not opposed to
it in principle, there are tradeoffs either way, and many limitations
imposed by the various platform keybinding situations.

**Comment by jackrusher** [comment]
Just dropping in to +1 Arne's suggestion that the keybind popup should have a shorter timer. I've watched several beginners now who never see it because it doesn't come up fast enough.

**Comment by jackrusher** [comment]
@plexus A quick note to mention that M1-left/right don't do exactly the same thing. `M1-left` expands the region to the left, `right` to the right, `up` to the next higher form, and `down` contracts the region _in the order in which it was expanded_. Assuming the "stickiness" bugs get sorted out, I think this is quite nice because it involves very few concepts/bindings to do many operations.

**Comment by mhuebert** [comment]
Closing this, for more discussion on keybindings please see #158.
