### ISSUE TITLE
How do I comment out multiple lines of code?

### ISSUE THREAD

**Issue by daiyi** [mhuebert/maria#116]
I see I can use `ctr+/` (on linux) to comment out a single line of code, but I also expect all highlighted lines to be commented out when I use the shortcut.

![I'd like to comment multiple lines!](https://user-images.githubusercontent.com/1589186/30881206-452a63aa-a305-11e7-8634-fd8b1b54bdf6.gif)

Maybe this is a bad habit of mine, but I like to "save" unused lines of code for "later" so it's nice to be able to multiline comment and uncomment! (also I find that most editors I use have this feature and I use it instinctively. Maybe this isn't as much of an expectation for beginners though.)

I also see there's an "ignore form" shortcut `ctrl+;`, but this seems to put my cursor into hand mode (????) instead of ignoring the form.

**Comment by daiyi** [comment]
Over the course of writing this issue I developed a new workflow of making a _new cell_ when I want to experiment, instead of commenting out, making my comment somewhat deprecated :'D

**Comment by mhuebert** [comment]
@daiyi thanks for the report! Good point, this isn't great behaviour.

re:cursor -  if your cursor happens to be above the form when you press `M1`, it will indeed become a hand. That is because `M1` (which is Command or Control depending on platform) selects the form under the cursor, and you can drag and drop selections using the mouse, hence the hand :-).

We should fix the line-comment behaviour (current behaviour is a bug) but it is also good to encourage the use of the uneval form (`#_`), as it keeps the commented-out form as data that we can manipulate, instead of turning it into a structureless string of text like line-commenting does. The downside to `#_` is that it only works on a single form at a time.

There is also another reason, specific to this editor. Behind the scenes, 'prose' blocks are in fact just consecutive top-level lines of comments. If you `;`-comment the top or bottom lines of a code block, then next time the doc is loaded, those commented lines could be treated as rich text field instead of code. The `uneval` form (`#_`) doesn't have this issue. 

If you press `M1-P` and type 'print' and select the "Doc/Print to console" command, you can see what the current document looks like as a string -- ie. all the rich text blocks will show up as markdown in commented lines. (Then you can see how `;`'ing code could cause it to be slurped up into the text field.)

**Comment by daiyi** [comment]
That's interesting, and thanks for explaining what's going on behind the scenes because it makes a lot of sense in that context!

I'm not sure if I was clear in my original note, but the `ctrl+;` aka "ignore form" isn't working for me, and gets the cell stuck in drag-and-drop mode.

Also your editor hijacks chrome on linux's open console shortcut `ctrl+shift+I` :P

**Comment by mhuebert** [comment]
> hijacks chrome on linux's open console shortcut ctrl+shift+I :P
ok, I've removed `ctrl-shift-i`, as it was redundant, `ctrl-i` is bound to "get info on form" :)

> ctrl+; aka "ignore form" isn't working for me, and gets the cell stuck in drag-and-drop mode.

hmm. I'm wondering if this is a keybinding issue, or if an error is being thrown somewhere.. 

could you try running this code in a cell:

```
(set! lark.commands.exec/debug? true)
```

...and then try pressing `ctrl-;` on a form again, and watch the console?

When working properly, it should print `"Executed command:" :edit/ignore-form`. If not, it means the key is being captured by the browser, a browser extension, or system. I just tested `ctrl-;` on windows 10 and it seems to work there but have no idea about linux.

**Comment by daiyi** [comment]
This is all I get:
```
"Executed command:" :select/form-at-cursor
```

No printouts when I press `ctrl+;`, and then it gets stuck in hand mode, and oddly no printouts when I use hand mode to move stuff around too. It logs other stuff like undo and cursor movements.

**Comment by mhuebert** [comment]
I've bound `M1-/` to `:edit/ignore-form` (that's `#_`) and `M1-Shift-/` to `:edit/comment-line`. That way the most common/expected comment binding defaults to the recommended behaviour.

The `#_` command should now be more reliable, and lenient: if the cursor is in the middle of whitespace, it will target the nearest non-whitespace form to the left.

I think a further improvement would be to uneval all the forms contained in or touched by the current selection.

**Comment by daveliepmann** [comment]
`ctrl-;` now works as expected for me using @daiyi's example from above. I think we can close.
