### ISSUE TITLE
Wrong arguments to `circle` doesn't cause error

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#117]
It seems wrong that `(circle "a")` produces no error, no shape, nothing returned at all. Same with `(circle [])`.

**Comment by jackrusher** [comment]
N.B. It does produce a bunch of errors at the JS console. The problem is that the shapes library doesn't check to make sure the parameter is a `number?`, so it ends up building a bogus SVG with various dimensions set to "a".

**Comment by mhuebert** [comment]
Do we want to do runtime checks for this kind of thing?

**Comment by jackrusher** [comment]
The `shapes` should probably check their arguments. I suppose we could just write up some `spec`s?

**Comment by mhuebert** [comment]
for `spec` to be useful in that we we need to use `instrument!`, then we get a further benefit of better error messages throughout, at the cost that intensive instrumentation brings. But it has some extra dependencies beyond regular usage of spec, and last time I tried, I couldn't get it to work because of some glitches introduced by that alpha namespace renaming event. maybe it has settled down by now.

- [ ] attempt to enable spec `instrument!`

when we get that working we will probably want to `spec` all of our userland stuff.

**Comment by jackrusher** [comment]
In the short term, we should probably just add some checks to the Shapes library.

**Comment by jackrusher** [comment]
Fix pushed.

**Comment by daveliepmann** [comment]
Please disregard above reference. Commit 5f32c7d has nothing to do with this issue. I typoed "177".
