### ISSUE TITLE
Share url times out

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#125]
### Issue:

Maybe I'm doing this wrong :) Jack showed me the share feature yesterday which is just oh so cool 😍 

e.g. http://share.maria.cloud/gist/bba60540e714b31dcac02eb7cdf02fbc/c999f04e742adcfc15c38f2e7e535e945a798a2a/0

Now I have an updated version of the post

https://dev.maria.cloud/gist/bba60540e714b31dcac02eb7cdf02fbc?eval=true

That I'm trying to share with this URL.

https://share.maria.cloud/gist/bba60540e714b31dcac02eb7cdf02fbc/26cd71ae38c891209601092c2758c8362903f773/2 

But that request times out.

### Environment:

  - Browser: Firefox Nightly
  - Platform (Mac/Windows/Linux): Linux

**Comment by jackrusher** [comment]
It is almost certainly a bug, and equally likely to be my fault. :)

**Comment by jackrusher** [comment]
Hm. Not really sure what the problem was. I couldn’t reproduce it locally, and couldn’t get it to do it again after I pushed my latest code to the server. That said, this code is fresh, hot and unstable, so weirdness and outages are to be expected.

In the meantime, there's been a notable addition to the API:

http://share.maria.cloud/shorten/bba60540e714b31dcac02eb7cdf02fbc/26cd71ae38c891209601092c2758c8362903f773/2

… returns text like:

60a9dc

… which can be used like so (note the `/s`):

http://share.maria.cloud/s/60a9dc

Also, the titles contain the gist "filename" and username of the maker, both of which are also included in the "Twitter card" preview. Hopefully I'll have time to wire up support for preview screenshots tomorrow.

**Comment by plexus** [comment]
this seems to no longer be an issue

**Comment by plexus** [comment]
also yay for the share button 🎉

**Comment by jackrusher** [comment]
@plexus getting closer... there's a known bug on share for docs containing comments, but that'll be sorted by this afternoon. :)
