### ISSUE TITLE
[Firefox] Ctrl-p and Ctrl-Shift-p are in use by the browser

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#132]
### Issue:

Ctrl-p / Ctrl-Shift-p, which both should bring up the "search command" dialog, are instead captured by Firefox

- Ctrl-p : print dialog
- Ctrl-Shift-p : New private window

### Environment:

  - Browser: Firefox nightly
  - Platform: Linux

**Comment by mhuebert** [comment]
Would you mind trying Ctrl-p on this page? https://keys-test.lark.cloud/?library=Keypress&keystring=M1%2520p

If it is successfully captured, it will say 'captured', otherwise you will see the print dialog as before.

it's a little keybindings test env I set up and this will tell us if the 'Keypress' lib does a better job of capturing "ctrl-p" than the code I was using before.

**Comment by plexus** [comment]
Yes, that worked!

**Comment by mhuebert** [comment]
We're now using a Keypress.js fork (pushed to dev) which should work the same as that test page. (We can intercept ctrl-p, but it looks impossible to intercept ctrl-shift-p.)

Closing for now, feel free to reopen if not resolved on dev.
