### ISSUE TITLE
[minor] pressing backspace inside empty string should delete string

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#137]
- start a new code block
- press " -> this inserts "" and puts the cursor inside the string
- press backspace (oh wait I didn't want to write a string), now the second string quote is still there

What should happen when the string is not empty is debatable. It all depends on how "paredit-like" you want editing on strings to be

e.g.

- do nothing, just move the cursor (the paredit way)
- unwrap the string -> analogous to how deleting an open paren works now
- delete the whole string?
- just delete the quote?

**Comment by mhuebert** [comment]
Agree that backspace in the empty string should remove it.

I think backspace at the beginning of a non-empty string should just move the cursor out, like paredit. it's unlikely that you'd want to use string data as code, so i don't think `unwrap` would be that useful, and deleting the string is already as simple as M1-Backspace (since M1 selects the whole string).
