### ISSUE TITLE
Hard to type negative numbers

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#150]
- Create code block
- Type `-1`

Expected: code block contains `-1`

Actual: code block contains `->`

### Environment:

  - Browser: Firefox, Chrome
  - Platform: Linux

**Comment by mhuebert** [comment]
This problem came up for me as well. I liked the idea of being able to select autocomplete suggestions by number, but gets in the way of symbols like this. One can press `esc` to get rid of the autocomplete box, but that's awkward.

We could special-case `-` as a prefix, or ditch select-by-number entirely..

**Comment by daveliepmann** [comment]
I encountered this bug too.

>We could special-case `-` as a prefix 

This could work, but won't there be other situations where I want to type a number with the autocomplete open?

>[we could] ditch select-by-number entirely..

Many tools use `tab` or `enter` to autocomplete using the selected autocomplete option, with selection of options handled by up-down arrows.
