### ISSUE TITLE
Wonky sexp detection

### ISSUE THREAD

**Issue by plexus** [mhuebert/maria#19]
Seems the code to detect the start/end of the current sexp is still a bit wonky. See the video:

https://youtu.be/NIHWV3FH808

Also seeing a lot of these in the browser console

    Error: Unmatched delimiter: %s("]") [at line 191, column 1]

**Comment by plexus** [comment]
Here's the code I had in the buffer

https://gist.github.com/c4fdf414aa83a90271a10e5e3b943e71

**Comment by plexus** [comment]
Seems I was missing a closing paren somewhere. This could arguably be handled more gracefully :)

**Comment by mhuebert** [comment]
You've certainly found a weakness: bracket highlighting, eval, and all
other commands rely on parsed Clojure code. when the code in the panel does
not represent a valid form, the reader chokes.

This is happening in the 'mhuebert/magic-tree' library, where we dig quite
deeply into the 'reading' process rather than using the standard clojure
reader. So we have some flexibility. It would be nice to have:

1. Accurate error messages, as soon as this occurs
2. Perhaps modify our reader to be more forgiving, and still create an AST
under 'broken' conditions when possible

**Comment by mhuebert** [comment]
Closing this just to move the discussion to #20.

Also, a bit of further explanation of the video you posted (thanks btw, that's a really clear way to show the problem!) - currently whenever we are unable to generate an AST, we re-use the AST from the last valid state of the document. This can lead to really weird effects where seemingly random characters are bolded: these are the 'ghosts of parentheses past' ;-).
