### ISSUE TITLE
Apropos hasn't been defined

### ISSUE THREAD

**Issue by anantpaatra** [mhuebert/maria#193]
### Issue:

Running `(apropos "colors")` or any other `apropos` call gives me:

![image](https://user-images.githubusercontent.com/9657386/37692622-a03ebe18-2c98-11e8-8870-00eaf9f9dd5f.png)

### Environment:

  - Browser: Firefox 59.0 (64-bit)
  - Platform (Mac/Windows/Linux): Linux
  

### URL to a gist replicating the issue (if possible/relevant)  
https://www.maria.cloud/intro

**Comment by daveliepmann** [comment]
Hi Anant, thanks for raising this question.

Since [apropros](https://clojuredocs.org/clojure.repl/apropos) is in the [clojure.repl namespace](https://clojuredocs.org/clojure.repl), it has to be explicitly loaded. Leiningen does this, so `(apropos "foo")` is automatically available at the command line REPL with `lein repl`, but we (like CIDER's editor-integrated REPL) do not. But it seems like it would be a nice feature that I'll add to a list of possible enhancements.

>URL to a gist replicating the issue (if possible/relevant)
>https://www.maria.cloud/intro

There seem to be two things going on here. First, it appears you're using an outdated version of that URL, since the wording we use in that section has been changed. If you want the fresh version (which overwrites any of your changes!) press "Revert" at the top. (We're working on improving the UI to make this more obvious.) 

Second, the code we provide in that section is `(colors-named "yellow")`. We don't use `apropos` in the introduction. It's fine to experiment, but that URL doesn't replicate the issue.

**Comment by anantpaatra** [comment]
> There seem to be two things going on here. First, it appears you're using an outdated version of that URL, since the wording we use in that section has been changed. If you want the fresh version (which overwrites any of your changes!) press "Revert" at the top. (We're working on improving the UI to make this more obvious.)

Did that and it updated the document. It seems I was mistaken and the `apropos` wasn't there in the first place? I must have added fiddling with the document before. Sorry about that.

Yes, not only that button escaped me completely but I would not understand it's application straight away. Great to know there are improvements coming. This is an _awesome_ application with the potential to be a modern Dr. Racket but for the Clojure world. Closing it now.

Closing the issue but just noticed the URL remains with the same wording. Thanks.
