### ISSUE TITLE
Highlight or color-code error message output

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#2]
When an evaluation produces an error, it might be nice for the output to be color-coded, highlighted, or marked in some other way that alerts the user that the output of evaluation is [abnormal](https://www.youtube.com/watch?v=inqdiNVzQcc).

Inspiration from [Intro to Racket with Pictures](http://docs.racket-lang.org/quick/):
>Note that DrRacket highlights in pink the expression that triggered the error (but pink highlighting is not shown in this documentation).

**Comment by mhuebert** [comment]
+1
Opinion on whether to do the highlighting in the REPL side, where we repeat
the evaluated source, or the left-hand side? (Much easier in the REPL)

**Comment by daveliepmann** [comment]
Long-term it would be ideal to have the failing code be marked on the left, e.g. underlined with a red squiggle. For now just marking the message (and perhaps the code?) on the right should be plenty.

Of course it will take some experimentation to find our favorite combination of font-weight, color, and perhaps an "error" icon to mark the event.

**Comment by mhuebert** [comment]
cc: @jackrusher 

Added error and warning highlighting to source display in REPL. Highlighting is the same as cursor/bracket highlighting - for collections, we highlight the edges, for 'solid' nodes we highlight the entire node. Feedback welcome.

I created a gist with some error examples to try it out:
https://gist.github.com/mhuebert/5a7d8165ca20ab5f391c1fa7e6ae6253

### what to highlight

When we implement error handling, we will probably want to be able to decide what to highlight based on the error itself (we can figure out a good interface for doing this later). Eg/ when evaluating `(mapv nil [1])`, `mapv` is highlighted even though `nil` is the problem. 

### screenshot 

<img width="1081" alt="screen shot 2017-05-29 at 1 39 50 pm" src="https://cloud.githubusercontent.com/assets/165223/26548413/5c77a5ee-4474-11e7-8804-34bf4ab9bfc3.png">

### error sources 

There are three distinct sources of errors:

1. Compile-time errors - we get the line/col from the ClojureScript compiler
2. Warnings - we get the line/col from the ClojureScript compiler. we currently treat warnings as errors. we probably want to be able to control this on a per-warning basis.
3. Evaluation errors - we use inline source mapping to get the errors, this is implemented in cljs-live and will behave differently across browsers as they handle stacks differently. 

### position indexing 

Line/column indexing has to be handled with care because lines and columns from the Clojure reader are 1-indexed whereas the rest of the relevant universe is zero-indexed. Something to keep in mind later. Currently the only place where this is handled directly is in [cljs-live](https://github.com/mhuebert/cljs-live/blob/master/src/cljs_live/eval.cljs#L108).

**Zero-indexed** positions:
- CodeMirror
- magic-tree zippers/nodes
- Source maps created via `cljs.source-map`

**1-indexed** positions:
- ClojureScript reader
- ^^ errors and warnings returned by the ClojureScript compiler

**Comment by mhuebert** [comment]
For errors, switched to a light red background for the entire output area + a thick black underline for the error positions. Should be easier on the eyes.

Screenshot:
<img width="1076" alt="screenshot 2017-05-30 13 45 14" src="https://cloud.githubusercontent.com/assets/165223/26581741/5b21d7e4-453e-11e7-86ae-3cd3ba848ce8.png">
