### ISSUE TITLE
Small typo in Learn Clojure with Shapes tutorial

### ISSUE THREAD

**Issue by rafapaezbas** [mhuebert/maria#238]
I found a small typo in the "Learn Clojure with Shapes.cljs" tutorial.  Check the paragraph:

"The above function needs its arguments to be shapes, and it is willing to accept any number of them. We used apply as a bridge **between between** a function that wants many arguments and a collection of those arguments as a single value."

The word _between_ is repeated.

  - Browser: Every browser.
  - Platform (Mac/Windows/Linux): Every platform.

**Comment by daveliepmann** [comment]
Sharp eye. Thanks for letting us know! 

It should be fixed now — if you still see the typo, it's probably because you've made changes to the intro and so are operating on a fork. *If* you're willing to lose those changes, the "Revert" button in the top menu should reset your state to what's in the curriculum. Cheers!
