### ISSUE TITLE
Functions should pretty print when their value is taken

### ISSUE THREAD

**Issue by jackrusher** [mhuebert/maria#30]
If I put `what-is` alone on a line and eval it, I get a big blob of Javascript in the right hand pane. We should intercept this sort of evaluation and insert the source for the function if it's available or otherwise some text saying that it's a `fn` for which we can't show the source.

**Comment by mhuebert** [comment]
At first glance, this will be relatively simple for functions that are `def`'d (after dealing with #31) because the var keeps file and positional info.

The only way I can think to do this for anonymous functions would be to do a reverse-chronological text search of all the JS we have compiled in the current session (this is the same log we will start keeping via #31), looking for the function's source , and then, since all the compiled JS is source-mapped, we can get back to the original.
