### ISSUE TITLE
Editor behavior (keymap, selection)

### ISSUE THREAD

**Issue by jackrusher** [mhuebert/maria#35]
I'm documenting my preferred editor key/mouse behavior [in the wiki](https://github.com/mhuebert/maria/wiki/Key-and-mouse-Interaction). Some of these key bindings are time tested Lisp classics, others are things I'm hoping we can do better than anyone else has. :)

**Comment by mhuebert** [comment]
some notes re: the recent which-key ui push:

- for displaying keys, currently using unicode symbols for keys (eg. ^⌘⇧⎇) rather than emacs-style upper-case letters (so ⌘C instead of A-C). We can customize these to match the user's platform. Keys are still entered as strings, so "Cmd-C".
- key sequences (space-separated) are already parsed/supported by the data structure but behaviour has not been implemented.

**Comment by mhuebert** [comment]
Moving discussion to https://github.com/mhuebert/maria/issues/45
