### ISSUE TITLE
which-key improvements

### ISSUE THREAD

**Issue by jackrusher** [mhuebert/maria#45]
- it would be nice if `M-enter`/`M-S-enter` were documented there
- do we have an easy way to import the default CodeMirror bindings into the popup so they’re also documented? (for example, `M-up` jumps to top of buffer)
- M- reports a binding for `K` (`kill`) but it does nothing, I suppose because `C-k` is bound to `kill` and the bindings have been somehow unified?
- Safari `M-1`/`M-2` doesn't work, and I don't think we can fix it. Probably needs a new binding. :(
- Copy/Cut are "X selection" rather than "X at point"
- The "comment line" function behaves bizarrely in both Safari and Chrome (just uncomments the first line of the buffer, no matter where I am)
- would like to see `uneval` bound to `M-;`, `uneval-toplevel-form` (or `comment-toplevel-form`) bound to `M-A-;`
- Slurp is great, would love some barf to match! (Adding preferred bindings to wiki)

**Comment by mhuebert** [comment]
ok, putting this into a to-do list here that I can keep up to date with progress:

- [ ] document/def M-enter/M-S-enter
- [ ] document/def default CodeMirror bindings (eg. M-up)
- [ ] debug K (kill) (M- reports a binding for K (kill) but it does nothing, I suppose because C-k is bound to kill and the bindings have been somehow unified?)
- [ ] Change binding for M-1/M-2 (Safari M-1/M-2 doesn't work, and I don't think we can fix it.)
- [ ] Rename "X at point" to "X at current highlight"
- [ ] Fix "comment line" function (behaves bizarrely in both Safari and Chrome -- just uncomments the first line of the buffer, no matter where I am)
- [ ] would like to see uneval bound to M-;, uneval-toplevel-form (or comment-toplevel-form) bound to M-A-;
- [ ] add barf (to match `slurp`)

**Comment by mhuebert** [comment]
> M- reports a binding for K (kill) but it does nothing, I suppose because C-k is bound to kill and the bindings have been somehow unified?

Ah, yes, I was thinking we were going to unify `ctrl` and `command` so I preemptively unified them in which-key but that hasn't been implemented.

**Comment by jackrusher** [comment]
O, cool. I've never used the to-do functionality of the Github issue tracker. 👍🏻

**Comment by mhuebert** [comment]
I've just pushed an update (and published to https://dev.maria.cloud):

- Added `eval`, `eval-top-form`, and `eval-on-click` to registered commands
- Made the key-combos prettier
- `eval-on-click` is bound with option instead of command (command is used for multiple selections)
- Until we figure out how we want to handle Chromebooks, `command` / `meta` / `control` are treated as equivalent. This meets the expectations people had around evaluation (`ctrl` as the alternative to `command`) as well as copy/paste/save. Not set in stone but at least now behaviour is equivalent with what is shown in `which-key`.

Would like to wait for a bit of feedback/confirmation that nothing is broken before pushing to www.maria.cloud.

**Comment by daveliepmann** [comment]
I'm taking a look now

**Comment by daveliepmann** [comment]
I checked off "document/def M-enter/M-S-enter". Will continue to dig around but things look good.

**Comment by daveliepmann** [comment]
In Chrome on my Mac, command-1 seems to have *stopped* working in dev. In production it progressively selects greater code blocks; in dev it switches to leftmost tab.

**Comment by mhuebert** [comment]
OK, the command-1 not working in Chrome is a bug that I've just fixed, however it still doesn't intercept the command in Safari. What do you think of `command-]` for expand and `command-[` for shrink? 

Also - I'm getting crashes when I try to `slurp`, will debug.

**Comment by daveliepmann** [comment]
>What do you think of command-] for expand and command-[ for shrink?

If it's just for Safari, I think it's a fine workaround for now. My brain expects command-1 in Chrome, so preserving that is my short-sighted, selfish concern. :)

**Comment by mhuebert** [comment]
OK..

- Selection expand/shrink: command-1/2 are enabled in addition to ]/[. 
- In which-key, only the first keymap is displayed, so we can recommend the one that should work for everyone while retaining conveniences.
- I had to do a really ugly workaround to make it possible to hold down the command/meta key while pressing other keys multiple times -- I think some browsers don't support this, and that's why the closure key handler also doesn't allow it. So my workaround may not work for everyone.
- I've organized the key hints into columns, and added namespaces to the command names so that they're logically grouped. I also reduced the font size. I'm starting to like it.

Everything seems to be broken in Firefox... can't see which-key or use commands.

In the future we should only show commands that are relevant for the current mouse focus / activity.

**Comment by mhuebert** [comment]
I've pushed the latest version to https://www.maria.cloud because it fixes the infinite loop problem that was introduced a couple of weeks ago (caused by unbalanced parens). There is still some work to do around unmatched parens -- the parser returns an error with position information, but we have to show that to the user via a highlight.

This new version also includes another reformat of `which-key` which more aggressively groups commands and I hope will make it easier to scan and find what you're looking for.

**Comment by mhuebert** [comment]
Created separate issues for the remaining items (#51, #50)
