### ISSUE TITLE
Can't copy code from right side of screen

### ISSUE THREAD

**Issue by ann-marieboehme** [mhuebert/maria#74]
![bildschirmfoto 2017-07-24 um 11 51 23](https://user-images.githubusercontent.com/30405948/28526906-413d2b3c-7089-11e7-82ff-2230db54dd6d.png)

Command + C also doesn't work, maybe because of the pop-up menu in the bottom of the screen. 🤗

**Comment by daveliepmann** [comment]
This is aggravating for me as well. I'm able to copy only with right-clicking the mouse, but not with `Command-c`.

**Comment by jackrusher** [comment]
This should cease to be a problem when we move to grouped code + output pairs, as the output "cards" won't contain the code that generated them. I'm not sure what we'll be able copying form the output cards, though, as they will be able to contain all sorts of non-code things.

**Comment by mhuebert** [comment]
I think this is a bug -- we should only intercept Command-C when the editing pane is focused.

**Comment by jackrusher** [comment]
@mhuebert When I highlight something in the output pane, focus remains on the input pane (what I type appears there, the cursor continues to blink, and so on).

**Comment by daveliepmann** [comment]
>I'm not sure what we'll be able copying form the output cards, though, as they will be able to contain all sorts of non-code things.

An instance from this weekend: I needed to copy error messages from the output pane to another window, to report the problem.

**Comment by jackrusher** [comment]
@daveliepmann what I was getting at is that I don't know what we're going to do with copying pictures, shapes and other non-text entities. :)

**Comment by mhuebert** [comment]
I've fixed half of this problem, and pushed new behaviour to https://dev.maria.cloud. 

Copy should now work on the right-hand side of the page for the view of the *output*, but still not in the 'view-only' codemirror panel which displays the source code you just evaluated. This is the bit where Jack noticed the weird behaviour that you can sort of select things, but not change the focus.

----

I modified `defcommand` to accept an `:intercept-when` predicate, in addition to the existing  `:when` predicate which indicates whether a command can be executed in the given context. 

Some commands, like copy/paste, should only intercept the event if they are 'context-active', while other commands, like 'save', should always prevent default (browser) behavior even if the doc is not currently 'saveable'.

Example of a command which will always intercept the event: 

```clj
(defcommand :doc/save
  "Save the current doc"
  {:bindings       ["Command-S"]

   ;; always intercept the keypress event
   :intercept-when true 

   ;; only consider this command 'executable' if the user is signed in 
   ;; and has permission to persist the current doc.
   :when           #(and (:signed-in? %) 
                         (#{:create :save} (persistence-mode (:doc-toolbar %))))}
  [{:keys [doc-toolbar]}]
  (persist! doc-toolbar))
```

**Comment by daveliepmann** [comment]
>it might be nice if selecting and copying a shape copied the source code to produce it, &c.

Added to roadmap/wishlist. This may be a bit far off but it's an absolutely stunning feature from DrRacket.

**Comment by mhuebert** [comment]
OK, final fix is pushed and deployed to dev.maria.cloud. You can now copy from the read-only editor on the right panel.

re: copy/pasting other stuff - this would be cool. for basic clojure data structures (including shapes, because they're just maps) -- ie. anything that can be represented by plain EDN -- the path forward is clear, because the output is a tree, each part of which has a nice serialized representation. Some unpleasant work to figure out cursor positions/selections and map that back to the tree, but this is exactly what we are building for future versions of the editor anyway, so we will probably have that code on hand.

I'm not sure what to do with vars, functions, atoms, namespaces, objects, and so on. Maybe those get copied as string placeholders which describe what _was_ there. if one was ambitious, for some of these types one could return code which would evaluate to return something similar.
