### ISSUE TITLE
Navigating by command or alt + arrow key brings up distracting which-key menu

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#82]
In dev.

I like to navigate text by holding `alt/option` down on my Mac and pressing arrow keys. I do this also with the command key. 

This causes the `which-key` menu to pop up and get in the way while I'm moving the cursor around. I'd prefer that this menu stay hidden if it detects that I'm using my arrow keys.

**Comment by jackrusher** [comment]
It sounds like this could be restated as "the timer for the popup should reset each time I press a key while holding a modifier, so long as the popup has not yet come up".

**Comment by daveliepmann** [comment]
I think that's correct. It may unfortunately be true that I like to hold the control key down while thinking of where I want to go next via arrow key, and that may be a more difficult conflict of use cases.

**Comment by mhuebert** [comment]
I think we can be a bit more conservative, and stop (rather than reset) the timer each time a non-modifier key is pressed. So to see `which-key` again after issuing a command (say, while holding down option), you would either add another modifier key, or lift & press the the modifier again. I've pushed this behaviour, we can try it out.
