### ISSUE TITLE
Edit/Slurp key binding not working

### ISSUE THREAD

**Issue by pedrorgirardi** [mhuebert/maria#95]
`Edit/Slurp` key binding on mac (`Cmd + Shift + K`) is not working, but it does work as expected when chosen from the `command panel`:

![screen shot 2017-09-11 at 14 30 23](https://user-images.githubusercontent.com/585191/30288121-f7446608-96fd-11e7-8094-bde6905734da.png)

![screen shot 2017-09-11 at 14 30 37](https://user-images.githubusercontent.com/585191/30288122-f765a3f4-96fd-11e7-88bd-0cf8c3aca6c4.png)

**Comment by mhuebert** [comment]
Hmm, what platform are you on?

**Comment by mhuebert** [comment]
I pushed a new version which involved a change to the modifier which temporarily expands a selection to top-level (`Cmd-Shift` instead of `Cmd-Option`). 

After refreshing the page, when you hold down Cmd+Shift, you should see the selection expand to cover the form. Then, adding `k` should slurp. If that doesn't work, I wonder if there could be another binding somewhere in your system (from an extension perhaps) that is interfering with `cmd-shift-k`?

**Comment by pedrorgirardi** [comment]
You are right, it seems to be something with my browser (maybe some extension in Chrome), because it works on Firefox :)  Sorry for not checking that before.

Thank you @mhuebert !
